spring.application.name=sistema-gestion-turnos

# Configuración H2 Database (para desarrollo local rápido)
spring.datasource.url=jdbc:h2:mem:turnosdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN

# Configuración por defecto de Mail (Modo Simulación)
spring.mail.host=localhost
spring.mail.port=25

# Configuración JWT (Clave Secreta limpia de 256 bits y Expiración de 24 horas en ms)
app.jwt.secret=ClaveSecretaSuperSeguraParaSistemaDeGestionDeTurnosMedicos2026SecretKey256Bits
app.jwt.expiration-ms=86400000

# Activar conexión a Google Calendar OAuth2
app.google.calendar.enabled=true
app.google.calendar.client-id=${GOOGLE_CLIENT_ID:}
app.google.calendar.client-secret=${GOOGLE_CLIENT_SECRET:}
app.google.calendar.redirect-uri=http://localhost:8080/api/google-calendar/callback

# Jackson: Serializar fechas y horas como strings ISO (no como arrays numéricos)
spring.jackson.serialization.write-dates-as-timestamps=false

# Server Port
server.port=8080
