@startuml

class Doctor{
    - nombre : String
    - apellido : String
    - horariodeEntrada : DateTime
    - horarioDeSalida : DateTime
    - especialidades : <Especialidad>
    - agenda : Calendario

}

enum Especialidad{

}


class Turno{
    - doctor : Doctor
    - dia : Date
    - horario : DateTime
    - duracion : DateTime
}

class Paciente{
    - nombre : String
    - apellido : String
    - dni : long
    - sexo : Sexo
    - mail : String
    - numeroDeTelefono : String
}

class Calendario{
    - fecha : Date
    - turnosDisponibles : <Turno>
    - turnosAsignados : <Turno>
}

class AsignadorDeTurno{

}

Calendario -> "1*" Turno
Doctor -> Calendario
Doctor -> Especialidad
Paciente -> Turno



@enduml