@startuml
class Paciente{
    - nombre : String
    - apellido : String
    - dni : long
    - sexo : Sexo
    - mail : String
    - numeroDeTelefono : String
    - tipoDeSangre : String
    - historiaClinica: <Turno>
    - recetas : Receta
}

enum Sexo{
    MASCULINO,
    FEMENINO
}

class Doctor{
    - nombre : String
    - apellido : String
}

class Turno{
    - doctor : Doctor
    - dia : Date
    - horario : Date
}

class Receta{
    - nombreMedicamento : Medicamento
    - descripcion : String
    - diaEmision : Date
    - diaDeCaducidad : Date
    - emitidaPor : Doctor
}

enum Medicamento{

}

Paciente -> Sexo
Paciente ->"0*" Turno
Doctor <- Turno
Receta -* Doctor
Receta -> Medicamento
Paciente -> "0*" Receta



@enduml